### ISSUE TITLE
 tidyABS_example mixes data

### ISSUE THREAD

**Issue by triadicaxis** [ianmoran11/tidyABS#13]
## copied from your example
df <-
  tidyABS_example("australian-industry.xlsx") %>%
  process_ABS_sheet(sheets = "Table_1") %>%
  assemble_table_components()

## check data types with str() or class()
class(df$value)
[1] "character" ## this should be numeric 

## on closer inspection we see why it's not
unique(df$value[duplicated(df$value)]) %>% head()
[1] "482" "485"  "MINING"                                    
[4] "MANUFACTURING" "1005" "ELECTRICITY, GAS, WATER AND WASTE SERVICES"

**Comment by ianmoran11** [comment]
Thanks @triadicaxis.  This was addressed here: https://github.com/ianmoran11/tidyABS/issues/10#issue-419276317

You may need to install the latest version. Note that `process_ABS_sheet` is now `process_sheet`.

The updated code will still store df$value as a character. This is because the centre values of the table may actually be characters in some cases and coercing them to numeric will lose information. I may add an argument to `process_sheet` to indicate whether a numeric value is expected. 

Here's your code running on the most recent version of tidyABS:

``` r
library(devtools)
library(tidyverse)
devtools::install_github("ianmoran11/tidyABS")
library(tidyABS)

df <-
  tidyABS_example("australian-industry.xlsx") %>%
  process_sheet(sheets = "Table_1") %>%
  assemble_table_components()

class(df$value)
#> [1] "character"

unique(df$value[duplicated(df$value)]) %>% head()
#> [1] "482"   "485"   "1005"  "23643" "114"   "104"
```

<sup>Created on 2019-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
